name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.4, "8.0", 8.1, 8.2, 8.3, 8.4]

    steps:
      - uses: actions/checkout@v4

      - name: test on PHP ${{ matrix.php }}
        run: docker build . --build-arg PHP_VERSION=${{ matrix.php }}
